### ISSUE TITLE
Is this app maintained?

### ISSUE THREAD

**Issue by enoch85** [buddebej/phonetrack-oc#2]
Hi,

Thanks for a great app! Just discovered that it can't be  found on Google Play. Does that mean that it's unmaintained?

A shame in that case, it's a perfect replacement for Google Timeline.

**Comment by Redsandro** [comment]
~~This project seems to have moved here~~
I am wrong. Disregard.

**Comment by Redsandro** [comment]
This project has moved here: https://gitlab.com/eneiluj/phonetrack-oc/

**Comment by enoch85** [comment]
Sorry, my bad.
